title: Elijah Agunbiade
logo: ![picture](https://github.com/ElijahAgunbiade/Portfolio/assets/173221971/cbcc899d-c2b1-47fc-bed2-d16f1ee81161)
#description: Aspiring Data Analyst
#show_downloads: false
theme: jekyll-theme-minimal
